var h;h||=typeof Module !== 'undefined' ? Module : {};h.Ne||(h.Ne=0);h.Ne++;
h.ENVIRONMENT_IS_PTHREAD||h.$ww||function(a){function b(n,p,u,q){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(n,function(x,B){x?q(x):u(B.buffer)});else{var t=new XMLHttpRequest;t.open("GET",n,!0);t.responseType="arraybuffer";t.onprogress=function(x){var B=p;x.total&&(B=x.total);if(x.loaded){t.de?h.ve[n].loaded=x.loaded:(t.de=!0,h.ve||(h.ve={}),h.ve[n]={loaded:x.loaded,total:B});var G=B=x=0,E;for(E in h.ve){var S=h.ve[E];
x+=S.total;B+=S.loaded;G++}x=Math.ceil(x*h.Ne/G);h.setStatus&&h.setStatus(`Downloading data... (${B}/${x})`)}else!h.ve&&h.setStatus&&h.setStatus("Downloading data...")};t.onerror=function(){throw Error("NetworkError for: "+n);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)u(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}}function c(n){console.error("package error:",n)}function d(){function n(t,x,B){this.start=t;this.end=
x;this.audio=B}function p(t){if(!t)throw"Loading data file failed."+Error().stack;if(t.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;t=new Uint8Array(t);n.prototype.ze=t;t=a.files;for(var x=0;x<t.length;++x)n.prototype.de[t[x].filename].onload();h.removeRunDependency("datafile_wasm/basque.data")}h.FS_createPath("/","assets",!0,!0);h.FS_createPath("/assets","audio",!0,!0);h.FS_createPath("/assets","data",!0,!0);h.FS_createPath("/assets","fonts",!0,!0);h.FS_createPath("/assets",
"icons",!0,!0);h.FS_createPath("/assets/icons","basque_logo.iconset",!0,!0);h.FS_createPath("/assets","images",!0,!0);n.prototype={de:{},open:function(t,x){this.name=x;this.de[x]=this;h.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.finish(this.ze.subarray(this.start,this.end))},finish:function(t){h.FS_createDataFile(this.name,null,t,!0,!0,!0);h.removeRunDependency(`fp ${this.name}`);this.de[this.name]=null}};for(var u=a.files,q=0;q<u.length;++q)(new n(u[q].start,u[q].end,
u[q].audio||0)).open("GET",u[q].filename);h.addRunDependency("datafile_wasm/basque.data");h.mf||(h.mf={});h.mf["wasm/basque.data"]={dg:!1};m?(p(m),m=null):g=p}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==
typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=h.locateFile?h.locateFile("basque.data",""):"basque.data",f=a.remote_package_size,g=null,m=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;m||b(e,f,function(n){g?(g(n),g=null):m=n},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))}({files:[{filename:"/assets/audio/Basque_sample_music.ogg",
start:0,end:4240906,audio:1},{filename:"/assets/data/map_attributes.txt",start:4240906,end:4243410},{filename:"/assets/data/map_layout.txt",start:4243410,end:4270941},{filename:"/assets/data/map_layout_0.txt",start:4270941,end:4298472},{filename:"/assets/data/map_layout_1.txt",start:4298472,end:4326003},{filename:"/assets/data/map_layout_2.txt",start:4326003,end:4353042},{filename:"/assets/data/map_layout_3.txt",start:4353042,end:4380085},{filename:"/assets/data/map_layout_4.txt",start:4380085,end:4407128},
{filename:"/assets/data/map_layout_5.txt",start:4407128,end:4434171},{filename:"/assets/data/map_layout_6.txt",start:4434171,end:4461214},{filename:"/assets/data/map_layout_7.txt",start:4461214,end:4488297},{filename:"/assets/data/map_layout_8.txt",start:4488297,end:4515424},{filename:"/assets/data/map_layout_9.txt",start:4515424,end:4542547},{filename:"/assets/data/map_library.txt",start:4542547,end:4542840},{filename:"/assets/fonts/BPtypewrite.ttf",start:4542840,end:4622012},{filename:"/assets/fonts/backpacker_license.pdf",
start:4622012,end:4928215},{filename:"/assets/icons/basque_logo.icns",start:4928215,end:5185942},{filename:"/assets/icons/basque_logo.ico",start:5185942,end:5288772},{filename:"/assets/icons/basque_logo.iconset/icon_1024x1024.png",start:5288772,end:5516561},{filename:"/assets/icons/basque_logo.iconset/icon_128x128.png",start:5516561,end:5536531},{filename:"/assets/icons/basque_logo.iconset/icon_128x128@2x.png",start:5536531,end:5588919},{filename:"/assets/icons/basque_logo.iconset/icon_16x16.png",
start:5588919,end:5591826},{filename:"/assets/icons/basque_logo.iconset/icon_16x16@2x.png",start:5591826,end:5596028},{filename:"/assets/icons/basque_logo.iconset/icon_256x256.png",start:5596028,end:5648416},{filename:"/assets/icons/basque_logo.iconset/icon_256x256@2x.png",start:5648416,end:5768787},{filename:"/assets/icons/basque_logo.iconset/icon_32x32.png",start:5768787,end:5772989},{filename:"/assets/icons/basque_logo.iconset/icon_32x32@2x.png",start:5772989,end:5781169},{filename:"/assets/icons/basque_logo.iconset/icon_512x512.png",
start:5781169,end:5901540},{filename:"/assets/icons/basque_logo.iconset/icon_512x512@2x.png",start:5901540,end:6129329},{filename:"/assets/icons/basque_logo.iconset/icon_64x64.png",start:6129329,end:6137509},{filename:"/assets/icons/basque_logo.iconset/icon_64x64@2x.png",start:6137509,end:6157479},{filename:"/assets/icons/basque_logo.iconset/icon_8x8@2x.png",start:6157479,end:6160386},{filename:"/assets/icons/basque_logo.png",start:6160386,end:6171029},{filename:"/assets/images/README.md",start:6171029,
end:6171215},{filename:"/assets/images/basque_logo.png",start:6171215,end:6172690},{filename:"/assets/images/basque_logo_scaled.png",start:6172690,end:6196554},{filename:"/assets/images/basque_logo_scaled_v2.png",start:6196554,end:6220329},{filename:"/assets/images/basque_logo_scaled_v3.png",start:6220329,end:6244453},{filename:"/assets/images/character.png",start:6244453,end:6248433},{filename:"/assets/images/tiles_packed.png",start:6248433,end:6255463}],remote_package_size:6255463});
var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},fa="object"==typeof window,ha="function"==typeof importScripts,ia="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ja=!fa&&!ia&&!ha,ka="";function la(a){return h.locateFile?h.locateFile(a,ka):ka+a}var ma,na,oa;
if(ia){var fs=require("fs"),pa=require("path");ka=ha?pa.dirname(ka)+"/":__dirname+"/";ma=(a,b)=>{a=qa(a)?new URL(a):pa.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};oa=a=>{a=ma(a,!0);a.buffer||(a=new Uint8Array(a));return a};na=(a,b,c,d=!0)=>{a=qa(a)?new URL(a):pa.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,f)=>{e?c(e):b(d?f.buffer:f)})};!h.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);
process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ra||a.context instanceof ra))throw a;});da=(a,b)=>{process.exitCode=a;throw b;};h.inspect=()=>"[Emscripten Module object]";"undefined"==typeof WebAssembly&&eval(fs.readFileSync(la("basque.wasm.js"))+"")}else if(fa||ha)ha?ka=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ka=document.currentScript.src),ka=0!==ka.indexOf("blob:")?ka.substr(0,ka.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ma=a=>{var b=new XMLHttpRequest;
b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(oa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),na=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var sa=h.print||console.log.bind(console),k=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;
h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var ta;h.wasmBinary&&(ta=h.wasmBinary);var va,wa=!1,xa,l,r,ya,za,v,w,y,z;function Aa(){var a=va.buffer;h.HEAP8=l=new Int8Array(a);h.HEAP16=ya=new Int16Array(a);h.HEAPU8=r=new Uint8Array(a);h.HEAPU16=za=new Uint16Array(a);h.HEAP32=v=new Int32Array(a);h.HEAPU32=w=new Uint32Array(a);h.HEAPF32=y=new Float32Array(a);h.HEAPF64=z=new Float64Array(a)}var Ba=h.INITIAL_MEMORY||536870912;
h.wasmMemory?va=h.wasmMemory:va=new WebAssembly.Memory({initial:Ba/65536,maximum:32768});Aa();Ba=va.buffer.byteLength;var Ca=[],Da=[],Ea=[],Fa=[],Ga=[];function Ha(){var a=h.preRun.shift();Ca.unshift(a)}var Ia=0,Ja=null,Ka=null;function La(){Ia++;h.monitorRunDependencies&&h.monitorRunDependencies(Ia)}function Ma(){Ia--;h.monitorRunDependencies&&h.monitorRunDependencies(Ia);if(0==Ia&&(null!==Ja&&(clearInterval(Ja),Ja=null),Ka)){var a=Ka;Ka=null;a()}}
function Na(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";k(a);wa=!0;xa=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Oa=a=>a.startsWith("data:application/octet-stream;base64,"),qa=a=>a.startsWith("file://"),Pa;Pa="basque.wasm";Oa(Pa)||(Pa=la(Pa));function Qa(a){if(a==Pa&&ta)return new Uint8Array(ta);if(oa)return oa(a);throw"both async and sync fetching of the wasm failed";}
function Ra(a){if(!ta&&(fa||ha)){if("function"==typeof fetch&&!qa(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Qa(a));if(na)return new Promise((b,c)=>{na(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Qa(a))}
function Sa(a,b,c){return Ra(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{k(`failed to asynchronously prepare wasm: ${d}`);if("undefined"!=typeof location){var e=location.search;if(0>e.indexOf("_rwasm=0")){location.href+=(e?e+"&":"?")+"_rwasm=0";return}}Na(d)})}
function Ta(a,b){var c=Pa;ta||"function"!=typeof WebAssembly.instantiateStreaming||Oa(c)||qa(c)||ia||"function"!=typeof fetch?Sa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k(`wasm streaming compile failed: ${e}`);k("falling back to ArrayBuffer instantiation");return Sa(c,a,b)}))}var A,C,Ua="basque.html.mem";
function Va(){Oa(Ua)||(Ua=la(Ua));if(ia||ja){var a=oa(Ua);r.set(a,1024)}else{La("memory initializer");var b=d=>{d.byteLength&&(d=new Uint8Array(d));r.set(d,1024);h.memoryInitializerRequest&&delete h.memoryInitializerRequest.response;Ma("memory initializer")},c=()=>{na(Ua,b,()=>{throw Error("could not load memory initializer "+Ua);})};h.memoryInitializerRequest?(a=()=>{var d=h.memoryInitializerRequest,e=d.response;200!==d.status&&0!==d.status?(console.warn("a problem seems to have happened with Module.memoryInitializerRequest, status: "+
d.status+", retrying "+Ua),c()):b(e)},h.memoryInitializerRequest.response?setTimeout(a,0):h.memoryInitializerRequest.addEventListener("load",a)):c()}}
var bb={387144:a=>{a=(a?D(r,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return Wa(Xa(a),"i8",Ya)},387369:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,387516:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,387750:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};
b.ee||("undefined"!==typeof AudioContext?b.ee=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ee=new webkitAudioContext),b.ee&&Za(b.ee));return void 0===b.ee?-1:0},388243:()=>h.SDL2.ee.sampleRate,388311:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.Be&&(clearTimeout(g.capture.Be),g.capture.Be=void 0);g.capture.Ie=g.ee.createMediaStreamSource(m);g.capture.ge=g.ee.createScriptProcessor(b,a,1);g.capture.ge.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),
g.capture.Me=n.inputBuffer,$a(c,[d]))};g.capture.Ie.connect(g.capture.ge);g.capture.ge.connect(g.ee.destination);g.capture.stream=m}var g=h.SDL2;g.capture.Ke=g.ee.createBuffer(a,b,g.ee.sampleRate);g.capture.Ke.getChannelData(0).fill(0);g.capture.Be=setTimeout(function(){g.capture.Me=g.capture.Ke;$a(c,[d])},b/g.ee.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&
navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},389963:(a,b,c,d)=>{var e=h.SDL2;e.audio.ge=e.ee.createScriptProcessor(b,0,a);e.audio.ge.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.af=f.outputBuffer,$a(c,[d]))};e.audio.ge.connect(e.ee.destination)},390373:(a,b)=>{for(var c=h.SDL2,d=c.capture.Me.numberOfChannels,e=0;e<d;++e){var f=c.capture.Me.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+
b+" samples!";if(1==d)for(var g=0;g<b;++g)ab(a+4*g,f[g]);else for(g=0;g<b;++g)ab(a+4*(g*d+e),f[g])}},390978:(a,b)=>{for(var c=h.SDL2,d=c.audio.af.numberOfChannels,e=0;e<d;++e){var f=c.audio.af.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=y[a+(g*d+e<<2)>>2]}},391458:a=>{var b=h.SDL2;if(a){void 0!==b.capture.Be&&clearTimeout(b.capture.Be);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();
for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.ge&&(b.capture.ge.onaudioprocess=function(){},b.capture.ge.disconnect(),b.capture.ge=void 0);void 0!==b.capture.Ie&&(b.capture.Ie.disconnect(),b.capture.Ie=void 0);void 0!==b.capture.Ke&&(b.capture.Ke=void 0);b.capture=void 0}else void 0!=b.audio.ge&&(b.audio.ge.disconnect(),b.audio.ge=void 0),b.audio=void 0;void 0!==b.ee&&void 0===b.audio&&void 0===b.capture&&(b.ee.close(),b.ee=void 0)},392630:(a,
b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.vf!==h.canvas&&(d.me=h.createContext(h.canvas,!1,!0),d.vf=h.canvas);if(d.w!==a||d.h!==b||d.Ff!==d.me)d.image=d.me.createImageData(a,b),d.w=a,d.h=b,d.Ff=d.me;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=v[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.yf!==a&&(d.xf=new Int32Array(a.buffer),d.zf=new Uint8Array(a.buffer),d.yf=a),a=d.xf,c=a.length,
a.set(v.subarray(b,b+c)),a=d.zf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.me.putImageData(d.image,0,0)},394099:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<
n;){var p=v[e];b[m]=p&255;b[m+1]=p>>8&255;b[m+2]=p>>16&255;b[m+3]=p>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(v.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=F(c.length+1);H(c,r,d,c.length+1);return d},395088:a=>{h.canvas&&(h.canvas.style.cursor=a?D(r,a):"")},395171:()=>{h.canvas&&(h.canvas.style.cursor="none")},395240:()=>window.innerWidth,395270:()=>window.innerHeight};
function ra(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var cb=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Za=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&cb(d,c,()=>{"suspended"===a.state&&a.resume()})})})},db=a=>{for(;0<a.length;)a.shift()(h)},eb=[],fb,I=a=>{var b=eb[a];b||(a>=eb.length&&(eb.length=a+1),eb[a]=b=fb.get(a));return b},$a=(a,b)=>{if("vi".includes("j")){var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else I(a).apply(null,b)},gb=h.noExitRuntime||
!0;function ab(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":l[a>>0]=b;break;case "i8":l[a>>0]=b;break;case "i16":ya[a>>1]=b;break;case "i32":v[a>>2]=b;break;case "i64":Na("to do setValue(i64) use WASM_BIGINT");case "float":y[a>>2]=b;break;case "double":z[a>>3]=b;break;case "*":w[a>>2]=b;break;default:Na(`invalid type for setValue: ${c}`)}}
var hb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,D=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&hb)return hb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
ib=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},jb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ib(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},kb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},lb=a=>{if("/"===
a)return"/";a=jb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},mb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ia)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}Na("initRandomDevice")},nb=a=>(nb=mb())(a);
function ob(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ib(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var pb=[],qb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},H=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>
12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function Xa(a,b){var c=Array(qb(a)+1);a=H(a,c,0,c.length);b&&(c.length=a);return c}var rb=[];function sb(a,b){rb[a]={input:[],output:[],re:b};tb(a,ub)}
var ub={open(a){var b=rb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close(a){a.tty.re.fsync(a.tty)},fsync(a){a.tty.re.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.re.cf)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.re.cf(a.tty)}catch(m){throw new J(29);}if(void 0===g&&0===e)throw new J(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.re.Re)throw new J(60);try{for(var e=0;e<d;e++)a.tty.re.Re(a.tty,b[c+
e])}catch(f){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},vb={cf(){a:{if(!pb.length){var a=null;if(ia){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}pb=Xa(a,!0)}a=
pb.shift()}return a},Re(a,b){null===b||10===b?(sa(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(sa(D(a.output,0)),a.output=[])},If(){return{Yf:25856,$f:5,Xf:191,Zf:35387,Wf:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Jf(){return 0},Kf(){return[24,80]}},wb={Re(a,b){null===b||10===b?(k(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(k(D(a.output,0)),a.output=[])}},yb=a=>{a=65536*
Math.ceil(a/65536);var b=xb(65536,a);b?(r.fill(0,b,b+a),a=b):a=0;return a};function zb(a,b){var c=a.ae?a.ae.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ae,a.ae=new Uint8Array(b),0<a.ce&&a.ae.set(c.subarray(0,a.ce),0))}
var K={oe:null,qe(){return K.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.oe||(K.oe={dir:{node:{ne:K.$d.ne,he:K.$d.he,lookup:K.$d.lookup,Je:K.$d.Je,rename:K.$d.rename,unlink:K.$d.unlink,rmdir:K.$d.rmdir,readdir:K.$d.readdir,symlink:K.$d.symlink},stream:{ue:K.be.ue}},file:{node:{ne:K.$d.ne,he:K.$d.he},stream:{ue:K.be.ue,read:K.be.read,write:K.be.write,We:K.be.We,Qe:K.be.Qe,jf:K.be.jf}},link:{node:{ne:K.$d.ne,he:K.$d.he,readlink:K.$d.readlink},
stream:{}},$e:{node:{ne:K.$d.ne,he:K.$d.he},stream:Ab}});c=Bb(a,b,c,d);Cb(c.mode)?(c.$d=K.oe.dir.node,c.be=K.oe.dir.stream,c.ae={}):32768===(c.mode&61440)?(c.$d=K.oe.file.node,c.be=K.oe.file.stream,c.ce=0,c.ae=null):40960===(c.mode&61440)?(c.$d=K.oe.link.node,c.be=K.oe.link.stream):8192===(c.mode&61440)&&(c.$d=K.oe.$e.node,c.be=K.oe.$e.stream);c.timestamp=Date.now();a&&(a.ae[b]=c,a.timestamp=c.timestamp);return c},fg(a){return a.ae?a.ae.subarray?a.ae.subarray(0,a.ce):new Uint8Array(a.ae):new Uint8Array(0)},
$d:{ne(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;Cb(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.ce:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.uf=4096;b.blocks=Math.ceil(b.size/b.uf);return b},he(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.ce!=b))if(0==
b)a.ae=null,a.ce=0;else{var c=a.ae;a.ae=new Uint8Array(b);c&&a.ae.set(c.subarray(0,Math.min(b,a.ce)));a.ce=b}},lookup(){throw Db[44];},Je(a,b,c,d){return K.createNode(a,b,c,d)},rename(a,b,c){if(Cb(a.mode)){try{var d=Eb(b,c)}catch(f){}if(d)for(var e in d.ae)throw new J(55);}delete a.parent.ae[a.name];a.parent.timestamp=Date.now();a.name=c;b.ae[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.ae[b];a.timestamp=Date.now()},rmdir(a,b){var c=Eb(a,b),d;for(d in c.ae)throw new J(55);
delete a.ae[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c in a.ae)a.ae.hasOwnProperty(c)&&b.push(c);return b},symlink(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},be:{read(a,b,c,d,e){var f=a.node.ae;if(e>=a.node.ce)return 0;a=Math.min(a.node.ce-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===l.buffer&&(f=!1);if(!d)return 0;a=
a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ae||a.ae.subarray)){if(f)return a.ae=b.subarray(c,c+d),a.ce=d;if(0===a.ce&&0===e)return a.ae=b.slice(c,c+d),a.ce=d;if(e+d<=a.ce)return a.ae.set(b.subarray(c,c+d),e),d}zb(a,e+d);if(a.ae.subarray&&b.subarray)a.ae.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ae[e+f]=b[c+f];a.ce=Math.max(a.ce,e+d);return d},ue(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ce);if(0>b)throw new J(28);return b},We(a,b,c){zb(a.node,b+c);a.node.ce=
Math.max(a.node.ce,b+c)},Qe(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.ae;if(e&2||a.buffer!==l.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;b=yb(b);if(!b)throw new J(48);l.set(a,b)}else c=!1,b=a.byteOffset;return{Of:b,sf:c}},jf(a,b,c,d){K.be.write(a,b,0,d,c,!1);return 0}}},Fb=(a,b,c)=>{var d=`al ${a}`;na(a,e=>{e||Na(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&Ma(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;
});d&&La(d)},Gb=h.preloadPlugins||[],Jb=(a,b,c,d)=>{"undefined"!=typeof Hb&&Ib();var e=!1;Gb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},Lb=(a,b,c,d,e,f,g,m,n,p)=>{function u(x){function B(G){p&&p();m||Kb(a,b,G,d,e,n);f&&f();Ma(t)}Jb(x,q,B,()=>{g&&g();Ma(t)})||B(x)}var q=b?ob(jb(a+"/"+b)):a,t=`cp ${q}`;La(t);"string"==typeof c?Fb(c,x=>u(x),g):u(c)},Mb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Nb=null,Ob={},Pb=[],Qb=1,Rb=null,Sb=!0,J=null,Db={};
function Tb(a,b={}){a=ob(a);if(!a)return{path:"",node:null};b=Object.assign({bf:!0,Se:0},b);if(8<b.Se)throw new J(32);a=a.split("/").filter(g=>!!g);for(var c=Nb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=Eb(c,a[e]);d=jb(d+"/"+a[e]);c.we&&(!f||f&&b.bf)&&(c=c.we.root);if(!f||b.Ee)for(f=0;40960===(c.mode&61440);)if(c=Ub(d),d=ob(kb(d),c),c=Tb(d,{Se:b.Se+1}).node,40<f++)throw new J(32);}return{path:d,node:c}}
function Vb(a){for(var b;;){if(a===a.parent)return a=a.qe.hf,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Wb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Rb.length}function Xb(a){var b=Wb(a.parent.id,a.name);if(Rb[b]===a)Rb[b]=a.xe;else for(b=Rb[b];b;){if(b.xe===a){b.xe=a.xe;break}b=b.xe}}
function Eb(a,b){var c;if(c=(c=Yb(a,"x"))?c:a.$d.lookup?0:2)throw new J(c,a);for(c=Rb[Wb(a.id,b)];c;c=c.xe){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.$d.lookup(a,b)}function Bb(a,b,c,d){a=new Zb(a,b,c,d);b=Wb(a.parent.id,a.name);a.xe=Rb[b];return Rb[b]=a}function Cb(a){return 16384===(a&61440)}function $b(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Yb(a,b){if(Sb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ac(a,b){try{return Eb(a,b),20}catch(c){}return Yb(a,"wx")}function bc(a,b,c){try{var d=Eb(a,b)}catch(e){return e.ke}if(a=Yb(a,"wx"))return a;if(c){if(!Cb(d.mode))return 54;if(d===d.parent||"/"===Vb(d))return 10}else if(Cb(d.mode))return 31;return 0}function cc(){for(var a=0;4096>=a;a++)if(!Pb[a])return a;throw new J(33);}
function dc(a){a=Pb[a];if(!a)throw new J(8);return a}function ec(a,b=-1){fc||(fc=function(){this.de={}},fc.prototype={},Object.defineProperties(fc.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.de.flags},set(c){this.de.flags=c}},position:{get(){return this.de.position},set(c){this.de.position=c}}}));a=Object.assign(new fc,a);-1==b&&(b=cc());a.fd=b;return Pb[b]=a}var Ab={open(a){a.be=Ob[a.node.rdev].be;a.be.open&&a.be.open(a)},ue(){throw new J(70);}};
function tb(a,b){Ob[a]={be:b}}function gc(a,b){var c="/"===b,d=!b;if(c&&Nb)throw new J(10);if(!c&&!d){var e=Tb(b,{bf:!1});b=e.path;e=e.node;if(e.we)throw new J(10);if(!Cb(e.mode))throw new J(54);}b={type:a,lg:{},hf:b,Nf:[]};a=a.qe(b);a.qe=b;b.root=a;c?Nb=a:e&&(e.we=b,e.qe&&e.qe.Nf.push(b))}function hc(a,b,c){var d=Tb(a,{parent:!0}).node;a=lb(a);if(!a||"."===a||".."===a)throw new J(28);var e=ac(d,a);if(e)throw new J(e);if(!d.$d.Je)throw new J(63);return d.$d.Je(d,a,b,c)}
function ic(a){return hc(a,16895,0)}function jc(a,b,c){"undefined"==typeof c&&(c=b,b=438);return hc(a,b|8192,c)}function lc(a,b){if(!ob(a))throw new J(44);var c=Tb(b,{parent:!0}).node;if(!c)throw new J(44);b=lb(b);var d=ac(c,b);if(d)throw new J(d);if(!c.$d.symlink)throw new J(63);c.$d.symlink(c,b,a)}function mc(a){var b=Tb(a,{parent:!0}).node;a=lb(a);var c=Eb(b,a),d=bc(b,a,!0);if(d)throw new J(d);if(!b.$d.rmdir)throw new J(63);if(c.we)throw new J(10);b.$d.rmdir(b,a);Xb(c)}
function nc(a){var b=Tb(a,{parent:!0}).node;if(!b)throw new J(44);a=lb(a);var c=Eb(b,a),d=bc(b,a,!1);if(d)throw new J(d);if(!b.$d.unlink)throw new J(63);if(c.we)throw new J(10);b.$d.unlink(b,a);Xb(c)}function Ub(a){a=Tb(a).node;if(!a)throw new J(44);if(!a.$d.readlink)throw new J(28);return ob(Vb(a.parent),a.$d.readlink(a))}function oc(a,b){a="string"==typeof a?Tb(a,{Ee:!0}).node:a;if(!a.$d.he)throw new J(63);a.$d.he(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function pc(a,b,c){if(""===a)throw new J(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=jb(a);try{e=Tb(a,{Ee:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new J(20);}else e=hc(a,c,0),d=!0;if(!e)throw new J(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!Cb(e.mode))throw new J(54);if(!d&&
(c=e?40960===(e.mode&61440)?32:Cb(e.mode)&&("r"!==$b(b)||b&512)?31:Yb(e,$b(b)):44))throw new J(c);if(b&512&&!d){c=e;c="string"==typeof c?Tb(c,{Ee:!0}).node:c;if(!c.$d.he)throw new J(63);if(Cb(c.mode))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(d=Yb(c,"w"))throw new J(d);c.$d.he(c,{size:0,timestamp:Date.now()})}b&=-131713;e=ec({node:e,path:Vb(e),flags:b,seekable:!0,position:0,be:e.be,Sf:[],error:!1});e.be.open&&e.be.open(e);!h.logReadFiles||b&1||(qc||={},a in qc||(qc[a]=1));return e}
function rc(a){if(null===a.fd)throw new J(8);a.Oe&&(a.Oe=null);try{a.be.close&&a.be.close(a)}catch(b){throw b;}finally{Pb[a.fd]=null}a.fd=null}function sc(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.be.ue)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.be.ue(a,b,c);a.Sf=[]}
function tc(a,b,c,d,e,f){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(Cb(a.node.mode))throw new J(31);if(!a.be.write)throw new J(28);a.seekable&&a.flags&1024&&sc(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new J(70);b=a.be.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function uc(){J||(J=function(a,b){this.name="ErrnoError";this.node=b;this.Qf=function(c){this.ke=c};this.Qf(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(a=>{Db[a]=new J(a);Db[a].stack="<generic error, no stack>"}))}var vc;function wc(a,b){a="string"==typeof a?a:Vb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=jb(a+"/"+c);try{ic(d)}catch(e){}a=d}}return d}
function xc(a,b,c,d){a=jb(("string"==typeof a?a:Vb(a))+"/"+b);c=Mb(c,d);return hc(a,(void 0!==c?c:438)&4095|32768,0)}function Kb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Vb(a),g=b?jb(a+"/"+b):a);a=Mb(d,e);g=hc(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}oc(g,a|146);b=pc(g,577);tc(b,c,0,c.length,0,f);rc(b);oc(g,a)}}
function yc(a,b,c,d){a=jb(("string"==typeof a?a:Vb(a))+"/"+b);b=Mb(!!c,!!d);yc.ff||(yc.ff=64);var e=yc.ff++<<8|0;tb(e,{open(f){f.seekable=!1},close(){d&&d.buffer&&d.buffer.length&&d(10)},read(f,g,m,n){for(var p=0,u=0;u<n;u++){try{var q=c()}catch(t){throw new J(29);}if(void 0===q&&0===p)throw new J(6);if(null===q||void 0===q)break;p++;g[m+u]=q}p&&(f.node.timestamp=Date.now());return p},write(f,g,m,n){for(var p=0;p<n;p++)try{d(g[m+p])}catch(u){throw new J(29);}n&&(f.node.timestamp=Date.now());return p}});
return jc(a,b,e)}function zc(a){if(!(a.Lf||a.Mf||a.link||a.ae)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ma)try{a.ae=Xa(ma(a.url),!0),a.ce=a.ae.length}catch(b){throw new J(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Ac(a,b,c,d,e){function f(){this.Pe=!1;this.de=[]}function g(q,t,x,B,G){q=q.node.ae;if(G>=q.length)return 0;B=Math.min(q.length-G,B);if(q.slice)for(var E=0;E<B;E++)t[x+E]=q[G+E];else for(E=0;E<B;E++)t[x+E]=q.get(G+E);return B}f.prototype.get=function(q){if(!(q>this.length-1||0>q)){var t=q%this.chunkSize;return this.df(q/this.chunkSize|0)[t]}};f.prototype.ze=function(q){this.df=q};f.prototype.Ye=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||
304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var t=Number(q.getResponseHeader("Content-length")),x,B=(x=q.getResponseHeader("Accept-Ranges"))&&"bytes"===x;q=(x=q.getResponseHeader("Content-Encoding"))&&"gzip"===x;var G=1048576;B||(G=t);var E=this;E.ze(S=>{var ea=S*G,ua=(S+1)*G-1;ua=Math.min(ua,t-1);if("undefined"==typeof E.de[S]){var kc=E.de;if(ea>ua)throw Error("invalid range ("+ea+", "+ua+") or no bytes requested!");if(ua>t-1)throw Error("only "+t+" bytes available! programmer error!");
var W=new XMLHttpRequest;W.open("GET",c,!1);t!==G&&W.setRequestHeader("Range","bytes="+ea+"-"+ua);W.responseType="arraybuffer";W.overrideMimeType&&W.overrideMimeType("text/plain; charset=x-user-defined");W.send(null);if(!(200<=W.status&&300>W.status||304===W.status))throw Error("Couldn't load "+c+". Status: "+W.status);ea=void 0!==W.response?new Uint8Array(W.response||[]):Xa(W.responseText||"",!0);kc[S]=ea}if("undefined"==typeof E.de[S])throw Error("doXHR failed!");return E.de[S]});if(q||!t)G=t=1,
G=t=this.df(0).length,sa("LazyFiles on gzip forces download of the whole file when length is accessed");this.rf=t;this.qf=G;this.Pe=!0};if("undefined"!=typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var m=new f;Object.defineProperties(m,{length:{get:function(){this.Pe||this.Ye();return this.rf}},chunkSize:{get:function(){this.Pe||this.Ye();return this.qf}}});var n=void 0}else n=c,m=void 0;var p=
xc(a,b,d,e);m?p.ae=m:n&&(p.ae=null,p.url=n);Object.defineProperties(p,{ce:{get:function(){return this.ae.length}}});var u={};Object.keys(p.be).forEach(q=>{var t=p.be[q];u[q]=function(){zc(p);return t.apply(null,arguments)}});u.read=(q,t,x,B,G)=>{zc(p);return g(q,t,x,B,G)};u.Qe=(q,t,x)=>{zc(p);var B=yb(t);if(!B)throw new J(48);g(q,l,B,t,x);return{Of:B,sf:!0}};p.be=u;return p}var Bc={},fc,qc;
function Cc(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":dc(a).path;if(0==b.length)throw new J(44);return jb(a+"/"+b)}var Dc=void 0;function Ec(){var a=v[+Dc>>2];Dc+=4;return a}
var Pc=(a,b)=>{Fc=a;Gc=b;if(Hc)if(Ic||=!0,0==a)Jc=function(){var d=Math.max(0,Kc+b-Lc())|0;setTimeout(Mc,d)};else if(1==a)Jc=function(){Nc(Mc)};else if(2==a){if("undefined"==typeof Oc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oc=function(d){c.push(d);ha?(void 0===h.setImmediates&&(h.setImmediates=[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}else Oc=setImmediate;Jc=function(){Oc(Mc)}}},Lc;Lc=()=>performance.now();
var Yc=(a,b,c,d,e)=>{!Hc||Na("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Hc=a;Qc=d;var f=Rc;Ic=!1;Mc=function(){if(!wa)if(0<Sc.length){var g=Sc.shift();g.eg(g.Vf);if(Tc){var m=Tc,n=0==m%1?m-1:Math.floor(m);Tc=g.bg?n:(8*m+(n+.5))/9}h.setStatus&&(g=h.statusMessage||"Please wait...",m=Tc,n=Uc.cg,m?m<n?h.setStatus(g+" ("+(n-m)+"/"+n+")"):h.setStatus(g):h.setStatus(""));
f<Rc||setTimeout(Mc,0)}else if(!(f<Rc))if(Vc=Vc+1|0,1==Fc&&1<Gc&&0!=Vc%Gc)Jc();else{0==Fc&&(Kc=Lc());if(!(wa||h.preMainLoop&&!1===h.preMainLoop())){if(!wa)try{a(),Wc()}catch(p){Xc(p)}h.postMainLoop&&h.postMainLoop()}f<Rc||("object"==typeof SDL&&SDL.audio&&SDL.audio.Pf&&SDL.audio.Pf(),Jc())}};e||(b&&0<b?Pc(0,1E3/b):Pc(1,1),Jc());if(c)throw"unwind";},Xc=a=>{a instanceof ra||"unwind"==a||da(1,a)},Zc=a=>{xa=a;if(!gb){if(h.onExit)h.onExit(a);wa=!0}da(a,new ra(a))},$c=a=>{xa=a;Zc(a)},Wc=()=>{if(!gb)try{var a=
xa;xa=a;Zc(a)}catch(b){Xc(b)}},ad=a=>{setTimeout(()=>{if(!wa)try{a(),Wc()}catch(b){Xc(b)}},1E4)},Ic=!1,Jc=null,Rc=0,Hc=null,Qc=0,Fc=0,Gc=0,Vc=0,Sc=[],Uc={},Kc,Mc,Tc,bd=!1,cd=!1,dd=[];
function Ib(){function a(){cd=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!ed){ed=!0;Gb.push({canHandle:function(c){return!h.kg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:fd(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:fd(d)}));var m=URL.createObjectURL(g),n=new Image;n.onload=()=>{n.complete||Na(`Image ${d} could not be decoded`);
var p=document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);gd[d]=p;URL.revokeObjectURL(m);e&&e(c)};n.onerror=()=>{k(`Image ${m} could not be decoded`);f&&f()};n.src=m}});Gb.push({canHandle:function(c){return!h.jg&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e&&e(c))}var g=!1,m=URL.createObjectURL(new Blob([c],{type:fd(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",u=0,q=0,t=0;t<c.length;t++)for(u=u<<8|c[t],q+=8;6<=q;){var x=u>>q-6&63;q-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==q?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],p+="=="):4==q&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+p;f(n)}};n.src=m;ad(()=>{f(n)})}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!cd&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var hd=!1,jd=void 0,kd=void 0;function ld(){if(!bd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var md=0;
function Nc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===md)md=b+1E3/60;else for(;b+2>=md;)md+=1E3/60;setTimeout(a,Math.max(md-b,0))}}function fd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var nd=[];function od(){var a=h.canvas;nd.forEach(b=>b(a.width,a.height))}
function pd(a,b,c){b&&c?(a.Uf=b,a.Ef=c):(b=a.Uf,c=a.Ef);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}kd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Hb={},Oc,ed,L=12288,qd=!1,rd=0,sd=0,td=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},ud={},vd,wd=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},xd=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},yd=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},zd=1,Ad=[],N=[],Bd=[],Cd=[],Dd=[],O=[],Ed=[],Fd=[],Gd=[],Hd={},Id=4;function P(a){Jd||=a}
var Kd=a=>{for(var b=zd++,c=a.length;c<b;c++)a[c]=null;return b},Md=(a,b)=>{a.de||(a.de=a.getContext,a.getContext=function(d,e){e=a.de(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Ld(c,b):0},Ld=(a,b)=>{var c=Kd(Fd),d={handle:c,attributes:b,version:b.gf,se:a};a.canvas&&(a.canvas.ye=d);Fd[c]=d;("undefined"==typeof b.Bf||b.Bf)&&Nd(d);return c},Pd=a=>{Od=Fd[a];h.me=Q=Od&&Od.se},Nd=a=>{a||=Od;if(!a.Gf){a.Gf=!0;var b=a.se;wd(b);xd(b);yd(b);b.pe=
b.getExtension("EXT_disjoint_timer_query");b.ig=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}};function Qd(){var a=Q.getSupportedExtensions()||[];return a=a.concat(a.map(b=>"GL_"+b))}
var Rd={},Jd,Od,Sd=a=>{var b=qb(a)+1,c=F(b);c&&H(a,r,c,b);return c},Td=[],Ud=(a,b)=>{Td.length=0;for(var c;c=r[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Td.push(112==c?w[b>>2]:105==c?v[b>>2]:z[b>>3]);b+=d?8:4}return Td},Vd=a=>{var b=R();a=a();T(b);return a},Wd=0;function Xd(){for(var a=Yd.length-1;0<=a;--a)Zd(a);Yd=[];$d=[]}var $d=[];
function ae(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in $d){var f=$d[e];if(f.Ue==a&&d(f.Xe,c))return}$d.push({Ue:a,lf:b,Xe:c});$d.sort((g,m)=>g.lf<m.lf)}function be(a){for(var b=0;b<$d.length;++b)$d[b].Ue==a&&($d.splice(b,1),--b)}function ce(){return navigator.userActivation?navigator.userActivation.isActive:Wd&&de.Ae}function ee(){if(ce())for(var a=0;a<$d.length;++a){var b=$d[a];$d.splice(a,1);--a;b.Ue.apply(null,b.Xe)}}
var Yd=[];function Zd(a){var b=Yd[a];b.target.removeEventListener(b.fe,b.Cf,b.ie);Yd.splice(a,1)}function fe(a){function b(d){++Wd;de=a;ee();a.le(d);ee();--Wd}if(!a.target)return-4;if(a.je)a.Cf=b,a.target.addEventListener(a.fe,b,a.ie),Yd.push(a),ge||(Fa.push(Xd),ge=!0);else for(var c=0;c<Yd.length;++c)Yd[c].target==a.target&&Yd[c].fe==a.fe&&Zd(c--);return 0}function he(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
function ie(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var je={},ge,de,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we={},xe=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],U=a=>{a=2<a?a?D(r,a):"":a;return xe[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},ze=a=>{var b=qb(a)+1,c=ye(b);H(a,r,c,b);return c},Ae=a=>Vd(()=>{var b=ye(8),c=b+4,d=ze(a.id);if(d=U(d))v[b>>2]=d.width,v[c>>2]=d.height;return[v[b>>2],v[c>>2]]}),Be=(a,b,c)=>{a=U(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ce=(a,b,c)=>{a.ag?Vd(()=>{var d=
ze(a.id);Be(d,b,c)}):(a.width=b,a.height=c)},De=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Ce(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=u,a.style.paddingTop=q,a.style.paddingBottom=t,a.style.marginLeft=
x,a.style.marginRight=B,a.style.marginTop=G,a.style.marginBottom=E,document.body.style.margin=S,document.documentElement.style.overflow=ea,document.body.scroll=ua,a.style.te=kc,a.ye&&a.ye.se.viewport(0,0,d,e),we.De&&I(we.De)(37,0,we.Ze))}var c=Ae(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,u=a.style.paddingRight,q=a.style.paddingTop,t=a.style.paddingBottom,x=a.style.marginLeft,B=a.style.marginRight,G=a.style.marginTop,
E=a.style.marginBottom,S=document.body.style.margin,ea=document.documentElement.style.overflow,ua=document.body.scroll,kc=a.style.te;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},Ee=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Fe=a=>0>xe.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Ge=(a,b)=>{if(0!=b.Te||0!=b.Le){De(a);var c=b.Rf?innerWidth:screen.width,d=b.Rf?innerHeight:
screen.height,e=Fe(a),f=e.width;e=e.height;var g=Ae(a),m=g[0];g=g[1];3==b.Te?(Ee(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Te&&(c*g<m*d?(f=g*c/m,Ee(a,(d-f)/2,0),d=f):(f=m*d/g,Ee(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Df&&(a.style.te="optimizeSpeed",a.style.te="-moz-crisp-edges",a.style.te="-o-crisp-edges",a.style.te="-webkit-optimize-contrast",
a.style.te="optimize-contrast",a.style.te="crisp-edges",a.style.te="pixelated");f=2==b.Le?devicePixelRatio:1;0!=b.Le&&(c=c*f|0,d=d*f|0,Ce(a,c,d),a.ye&&a.ye.se.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return ie()?-3:-1;we=b;b.De&&I(b.De)(37,0,b.Ze);return 0},He=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Ie=(a,b)=>
{z[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)z[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)z[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)v[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];v[a+1296>>2]=b.connected;v[a+1300>>2]=b.index;v[a+8>>2]=b.axes.length;v[a+12>>2]=b.buttons.length;H(b.id,r,a+1304,64);H(b.mapping,r,a+1368,64)},Je=(a,b,c)=>{(a|0)===a&&(a=a?D(r,a):"");a=ob(a);if(a=gd[a]){var d=
a.getContext("2d").getImageData(0,0,a.width,a.height),e=F(a.width*a.height*4);r.set(d.data,e);v[b>>2]=a.width;v[c>>2]=a.height;return e}return 0},Ke=[],Le=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=Q[c](),g=f&&Kd(d);f?(f.name=g,d[g]=f):P(1282);v[b+4*e>>2]=g}},Me=(a,b,c,d,e,f,g,m)=>{b=N[b];if(a=Q[a](b,c))d=m&&H(a.name,r,m,d),e&&(v[e>>2]=d),f&&(v[f>>2]=a.size),g&&(v[g>>2]=a.type)},Ne=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&P(1280);return;case 36345:d=0;break;case 34466:var e=
Q.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=Q.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":P(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:P(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:v[b+4*a>>2]=e[a];break;case 2:y[b+
4*a>>2]=e[a];break;case 4:l[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){P(1280);k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:P(1280);k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;w[b>>2]=c;w[b+4>>2]=(c-w[b>>2])/4294967296;break;case 0:v[b>>2]=d;break;case 2:y[b>>2]=d;break;case 4:l[b>>0]=d?1:0}}else P(1281)},Oe=(a,b,c)=>
{if(c){a=Q.pe.getQueryObjectEXT(Gd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d;w[c+4>>2]=(d-w[c>>2])/4294967296}else P(1281)},Pe=(a,b,c)=>{if(c){a=Q.pe.getQueryObjectEXT(Gd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else P(1281)},Qe=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Re=a=>{var b=a.Ce,c=a.pf,d;if(!b)for(a.Ce=b={},a.nf={},d=0;d<Q.getProgramParameter(a,35718);++d){var e=Q.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Qe(f);g=0<g?f.slice(0,g):f;var m=a.Ve;a.Ve+=e;c[g]=[e,
m];for(f=0;f<e;++f)b[m]=f,a.nf[m++]=g}},V=a=>{var b=Q.wf;if(b){var c=b.Ce[a];"number"==typeof c&&(b.Ce[a]=c=Q.getUniformLocation(b,b.nf[a]+(0<c?`[${c}]`:"")));return c}P(1282)},Se=(a,b,c,d)=>{if(c)if(a=N[a],Re(a),a=Q.getUniform(a,V(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:y[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b]}else P(1281)},Te=(a,b,c,d)=>{if(c)if(a=Q.getVertexAttrib(a,b),34975==b)v[c>>2]=a&&a.name;
else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:y[c>>2]=a;break;case 5:v[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b];break;case 5:v[c+4*b>>2]=Math.fround(a[b])}else P(1281)},Ue=(a,b,c,d,e)=>{a-=5120;a=1==a?r:4==a?v:6==a?y:5==a||28922==a?w:za;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Id;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)},Ve=[],We=[],
Xe=(a,b)=>{if(!ie())return-1;a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?ce()?Ge(a,b):b.Af?(ae(Ge,1,[a,b]),1):-2:-3:-4},Ye=(a,b)=>{var c={target:U(2),fe:"beforeunload",je:b,le:(d=event)=>{var e=I(b)(28,0,a);e&&=e?D(r,e):"";if(e)return d.preventDefault(),d.returnValue=e},ie:!0};return fe(c)},Ze=(a,b,c,d,e,f)=>{le||=F(256);a={target:U(a),fe:f,je:d,le:(g=event)=>{var m=g.target.id?g.target.id:"",n=le;H(he(g.target),r,n+0,128);H(m,r,n+128,128);I(d)(e,n,b)&&g.preventDefault()},ie:c};
return fe(a)},$e=(a,b,c,d,e)=>{ne||=F(280);return fe({target:a,fe:e,je:d,le:(f=event)=>{var g=ne,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;v[g>>2]=n;v[g+4>>2]=ie();var p=n?m:me,u=p&&p.id?p.id:"";H(he(p),r,g+8,128);H(u,r,g+136,128);v[g+264>>2]=p?p.clientWidth:0;v[g+268>>2]=p?p.clientHeight:0;v[g+272>>2]=screen.width;v[g+276>>2]=screen.height;n&&(me=m);I(d)(19,g,b)&&f.preventDefault()},ie:c})},af=(a,b,c,d,e)=>{oe||=
F(1432);b={target:U(2),Ae:!0,fe:e,je:c,le:(f=event)=>{var g=oe;Ie(g,f.gamepad);I(c)(d,g,a)&&f.preventDefault()},ie:b};return fe(b)},bf=(a,b,c,d,e,f)=>{pe||=F(176);a={target:U(a),Ae:!0,fe:f,je:d,le:g=>{var m=pe;z[m>>3]=g.timeStamp;var n=m>>2;v[n+2]=g.location;v[n+3]=g.ctrlKey;v[n+4]=g.shiftKey;v[n+5]=g.altKey;v[n+6]=g.metaKey;v[n+7]=g.repeat;v[n+8]=g.charCode;v[n+9]=g.keyCode;v[n+10]=g.which;H(g.key||"",r,m+44,32);H(g.code||"",r,m+76,32);H(g.char||"",r,m+108,32);H(g.locale||"",r,m+140,32);I(d)(e,m,
b)&&g.preventDefault()},ie:c};return fe(a)},cf=(a,b,c)=>{z[a>>3]=b.timeStamp;a>>=2;v[a+2]=b.screenX;v[a+3]=b.screenY;v[a+4]=b.clientX;v[a+5]=b.clientY;v[a+6]=b.ctrlKey;v[a+7]=b.shiftKey;v[a+8]=b.altKey;v[a+9]=b.metaKey;ya[2*a+20]=b.button;ya[2*a+21]=b.buttons;v[a+11]=b.movementX;v[a+12]=b.movementY;c=Fe(c);v[a+13]=b.clientX-c.left;v[a+14]=b.clientY-c.top},df=(a,b,c,d,e,f)=>{qe||=F(72);a=U(a);return fe({target:a,Ae:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,fe:f,je:d,le:(g=event)=>{cf(qe,g,a);
I(d)(e,qe,b)&&g.preventDefault()},ie:c})},ef=(a,b,c,d,e)=>{re||=F(260);return fe({target:a,fe:e,je:d,le:(f=event)=>{var g=re,m=document.pointerLockElement||document.de||document.tf||document.ze;v[g>>2]=!!m;var n=m&&m.id?m.id:"";H(he(m),r,g+4,128);H(n,r,g+132,128);I(d)(20,g,b)&&f.preventDefault()},ie:c})},ff=(a,b,c,d)=>{se||=F(36);a=U(a);return fe({target:a,fe:"resize",je:d,le:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=se;v[g>>2]=e.detail;v[g+4>>2]=f.clientWidth;v[g+8>>2]=f.clientHeight;
v[g+12>>2]=innerWidth;v[g+16>>2]=innerHeight;v[g+20>>2]=outerWidth;v[g+24>>2]=outerHeight;v[g+28>>2]=pageXOffset;v[g+32>>2]=pageYOffset;I(d)(10,g,b)&&e.preventDefault()}}},ie:c})},gf=(a,b,c,d,e,f)=>{te||=F(1696);a=U(a);return fe({target:a,Ae:"touchstart"==f||"touchend"==f,fe:f,je:d,le:g=>{for(var m,n={},p=g.touches,u=0;u<p.length;++u)m=p[u],m.ef=m.kf=0,n[m.identifier]=m;for(u=0;u<g.changedTouches.length;++u)m=g.changedTouches[u],m.ef=1,n[m.identifier]=m;for(u=0;u<g.targetTouches.length;++u)n[g.targetTouches[u].identifier].kf=
1;p=te;z[p>>3]=g.timeStamp;var q=p>>2;v[q+3]=g.ctrlKey;v[q+4]=g.shiftKey;v[q+5]=g.altKey;v[q+6]=g.metaKey;q+=7;var t=Fe(a),x=0;for(u in n)if(m=n[u],v[q]=m.identifier,v[q+1]=m.screenX,v[q+2]=m.screenY,v[q+3]=m.clientX,v[q+4]=m.clientY,v[q+5]=m.pageX,v[q+6]=m.pageY,v[q+7]=m.ef,v[q+8]=m.kf,v[q+9]=m.clientX-t.left,v[q+10]=m.clientY-t.top,q+=13,31<++x)break;v[p+8>>2]=x;I(d)(e,p,b)&&g.preventDefault()},ie:c})},hf=(a,b,c)=>{var d=xe[1];ue||=F(8);return fe({target:d,fe:"visibilitychange",je:c,le:(e=event)=>
{var f=ue,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);v[f>>2]=document.hidden;v[f+4>>2]=g;I(c)(21,f,a)&&e.preventDefault()},ie:b})},jf=(a,b,c,d)=>{ve||=F(104);return fe({target:a,Ae:!0,fe:"wheel",je:d,le:(e=event)=>{var f=ve;cf(f,e,a);z[f+72>>3]=e.deltaX;z[f+80>>3]=e.deltaY;z[f+88>>3]=e.deltaZ;v[f+96>>2]=e.deltaMode;I(d)(9,f,b)&&e.preventDefault()},ie:c})},kf={},mf=()=>{if(!lf){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==
typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in kf)void 0===kf[b]?delete a[b]:a[b]=kf[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);lf=c}return lf},lf,Ya=0,Wa=(a,b)=>{b=1==b?ye(a.length):F(a.length);a.subarray||a.slice||(a=new Uint8Array(a));r.set(a,b);return b};function Zb(a,b,c,d){a||=this;this.parent=a;this.qe=a.qe;this.we=null;this.id=Qb++;this.name=b;this.mode=c;this.$d={};this.be={};this.rdev=d}
Object.defineProperties(Zb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Mf:{get:function(){return Cb(this.mode)}},Lf:{get:function(){return 8192===(this.mode&61440)}}});uc();Rb=Array(4096);gc(K,"/");ic("/tmp");ic("/home");ic("/home/web_user");
(function(){ic("/dev");tb(259,{read:()=>0,write:(d,e,f,g)=>g});jc("/dev/null",259);sb(1280,vb);sb(1536,wb);jc("/dev/tty",1280);jc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=nb(a).byteLength);return a[--b]};yc("/dev","random",c);yc("/dev","urandom",c);ic("/dev/shm");ic("/dev/shm/tmp")})();
(function(){ic("/proc");var a=ic("/proc/self");ic("/proc/self/fd");gc({qe(){var b=Bb(a,"fd",16895,73);b.$d={lookup(c,d){var e=dc(+d);c={parent:null,qe:{hf:"fake"},$d:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=wc;h.FS_createDataFile=Kb;h.FS_createPreloadedFile=Lb;h.FS_unlink=nc;h.FS_createLazyFile=Ac;h.FS_createDevice=yc;
h.requestFullscreen=function(a,b){function c(){bd=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=ld,jd&&d.requestPointerLock(),bd=!0,kd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=w[SDL.screen>>2]|8388608),pd(h.canvas),od()):pd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),kd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=
w[SDL.screen>>2]&-8388609),pd(h.canvas),od()):pd(d));if(h.onFullScreen)h.onFullScreen(bd);if(h.onFullscreen)h.onFullscreen(bd)}jd=a;kd=b;"undefined"==typeof jd&&(jd=!0);"undefined"==typeof kd&&(kd=!1);var d=h.canvas;hd||(hd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,
d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=Nc;h.setCanvasSize=function(a,b,c){pd(h.canvas,a,b);c||od()};h.pauseMainLoop=function(){Jc=null;Rc++};
h.resumeMainLoop=function(){Rc++;var a=Fc,b=Gc,c=Hc;Hc=null;Yc(c,0,!1,Qc,!0);Pc(a,b);Jc()};h.getUserMedia=function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.me&&a==h.canvas)return h.me;var e;if(b){var f={antialias:!1,alpha:!1,gf:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Rd&&(e=Md(a,f)))var m=Fd[e].se}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof Q||Na("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.me=m,b&&Pd(e),h.Tf=b,dd.forEach(n=>n()),Ib());return m};for(var gd={},Q,X=0;32>X;++X)Ke.push(Array(X));var nf=new Float32Array(288);
for(X=0;288>X;++X)Ve[X]=nf.subarray(0,X+1);var of=new Int32Array(288);for(X=0;288>X;++X)We[X]=of.subarray(0,X+1);
var Df={W:(a,b,c,d)=>{Na(`Assertion failed: ${a?D(r,a):""}, at: `+[b?b?D(r,b):"":"unknown filename",c,d?d?D(r,d):"":"unknown function"])},N:function(a,b,c){Dc=c;try{var d=dc(a);switch(b){case 0:var e=Ec();if(0>e)return-28;for(;Pb[e];)e++;return ec(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ec(),d.flags|=e,0;case 5:return e=Ec(),ya[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return v[pf()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof Bc||
"ErrnoError"!==f.name)throw f;return-f.ke}},eb:function(a,b,c){Dc=c;try{var d=dc(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.re.If){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ec();v[e>>2]=25856;v[e+4>>2]=5;v[e+8>>2]=191;v[e+12>>2]=35387;for(var f=0;32>f;f++)l[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.re.Jf)for(e=Ec(),b=
[],f=0;32>f;f++)b.push(l[e+f+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=Ec();return v[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=Ec();if(!d.be.Hf)throw new J(59);return d.be.Hf(d,b,e);case 21523:if(!d.tty)return-59;d.tty.re.Kf&&(f=[24,80],e=Ec(),ya[e>>1]=f[0],ya[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof Bc||"ErrnoError"!==g.name)throw g;return-g.ke}},fb:function(a,b,c,d){Dc=d;try{b=b?D(r,b):
"";b=Cc(a,b);var e=d?Ec():0;return pc(b,c,e).fd}catch(f){if("undefined"==typeof Bc||"ErrnoError"!==f.name)throw f;return-f.ke}},_a:function(a){try{return a=a?D(r,a):"",mc(a),0}catch(b){if("undefined"==typeof Bc||"ErrnoError"!==b.name)throw b;return-b.ke}},cb:function(a,b){try{a=a?D(r,a):"";a:{try{var c=Tb(a,{Ee:!0}).node;if(!c)throw new J(44);if(!c.$d.ne)throw new J(63);var d=c.$d.ne(c)}catch(n){if(n&&n.node&&jb(a)!==jb(Vb(n.node))){var e=-54;break a}throw n;}v[b>>2]=d.dev;v[b+4>>2]=d.mode;w[b+8>>
2]=d.nlink;v[b+12>>2]=d.uid;v[b+16>>2]=d.gid;v[b+20>>2]=d.rdev;C=[d.size>>>0,(A=d.size,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[b+24>>2]=C[0];v[b+28>>2]=C[1];v[b+32>>2]=4096;v[b+36>>2]=d.blocks;var f=d.atime.getTime(),g=d.mtime.getTime(),m=d.ctime.getTime();C=[Math.floor(f/1E3)>>>0,(A=Math.floor(f/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[b+40>>2]=C[0];v[b+44>>2]=C[1];w[b+48>>
2]=f%1E3*1E3;C=[Math.floor(g/1E3)>>>0,(A=Math.floor(g/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[b+56>>2]=C[0];v[b+60>>2]=C[1];w[b+64>>2]=g%1E3*1E3;C=[Math.floor(m/1E3)>>>0,(A=Math.floor(m/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[b+72>>2]=C[0];v[b+76>>2]=C[1];w[b+80>>2]=m%1E3*1E3;C=[d.ino>>>0,(A=d.ino,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>
0))/4294967296)>>>0:0)];v[b+88>>2]=C[0];v[b+92>>2]=C[1];e=0}return e}catch(n){if("undefined"==typeof Bc||"ErrnoError"!==n.name)throw n;return-n.ke}},$a:function(a,b,c){try{return b=b?D(r,b):"",b=Cc(a,b),0===c?nc(b):512===c?mc(b):Na("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof Bc||"ErrnoError"!==d.name)throw d;return-d.ke}},gb:()=>1,Wa:()=>{throw Infinity;},Oc:()=>{Na("")},Oa:a=>{if(12448==a)return L=12288,1;L=12300;return 0},Sa:(a,b,c,d,e)=>{if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=
v[b>>2];if(12321==a)M.alpha=0<v[b+4>>2];else if(12325==a)M.depth=0<v[b+4>>2];else if(12326==a)M.stencil=0<v[b+4>>2];else if(12337==a)a=v[b+4>>2],M.antialias=0<a;else if(12338==a)a=v[b+4>>2],M.antialias=1==a;else if(12544==a)M.gg=12547!=v[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(v[e>>2]=1),c&&0<d&&(w[c>>2]=62002),L=12288,c=1):(L=12300,c=0)}return c},Fa:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;for(a=1;;){b=v[d>>2];if(12440==b)a=v[d+4>>2];else if(12344==b)break;else return L=12292,0;d+=8}if(2!=
a)return L=12293,0;M.gf=a-1;M.hg=0;vd=Md(h.canvas,M);if(0!=vd)return L=12288,Pd(vd),h.Tf=!0,dd.forEach(function(e){e()}),Pd(null),62004;L=12297;return 0},Ha:(a,b)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;L=12288;return 62006},Ga:(a,b)=>{if(62E3!=a)return L=12296,0;if(62004!=b)return L=12294,0;a=vd;Od===Fd[a]&&(Od=null);if("object"==typeof je)for(var c=Fd[a].se.canvas,d=0;d<Yd.length;++d)Yd[d].target!=c||Zd(d--);Fd[a]&&Fd[a].se.canvas&&(Fd[a].se.canvas.ye=void 0);Fd[a]=null;L=12288;
rd==b&&(rd=0);return 1},Ia:(a,b)=>{if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;sd==b&&(sd=0);td==b&&(td=0);L=12288;return 1},Xa:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return v[d>>2]=M.alpha?32:24,1;case 12321:return v[d>>2]=M.alpha?8:0,1;case 12322:return v[d>>2]=8,1;case 12323:return v[d>>2]=8,1;case 12324:return v[d>>2]=8,1;case 12325:return v[d>>2]=M.depth?24:0,1;case 12326:return v[d>>2]=M.stencil?8:
0,1;case 12327:return v[d>>2]=12344,1;case 12328:return v[d>>2]=62002,1;case 12329:return v[d>>2]=0,1;case 12330:return v[d>>2]=4096,1;case 12331:return v[d>>2]=16777216,1;case 12332:return v[d>>2]=4096,1;case 12333:return v[d>>2]=0,1;case 12334:return v[d>>2]=0,1;case 12335:return v[d>>2]=12344,1;case 12337:return v[d>>2]=M.antialias?4:0,1;case 12338:return v[d>>2]=M.antialias?1:0,1;case 12339:return v[d>>2]=4,1;case 12340:return v[d>>2]=12344,1;case 12341:case 12342:case 12343:return v[d>>2]=-1,
1;case 12345:case 12346:return v[d>>2]=0,1;case 12347:return v[d>>2]=0,1;case 12348:return v[d>>2]=1;case 12349:case 12350:return v[d>>2]=0,1;case 12351:return v[d>>2]=12430,1;case 12352:return v[d>>2]=4,1;case 12354:return v[d>>2]=0,1;default:return L=12292,0}},L:a=>{L=12288;return 0!=a&&1!=a?0:62E3},Da:()=>L,Qa:(a,b,c)=>{if(62E3!=a)return L=12296,0;b&&(v[b>>2]=1);c&&(v[c>>2]=4);qd=!0;L=12288;return 1},Ja:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=
c||0!=b&&62006!=b)return L=12301,0;Pd(d?vd:null);rd=d;td=b;sd=c;L=12288;return 1},Ca:(a,b)=>{if(62E3!=a)return L=12296,0;L=12288;if(ud[b])return ud[b];switch(b){case 12371:a=Sd("Emscripten");break;case 12372:a=Sd("1.4 Emscripten EGL");break;case 12373:a=Sd("");break;case 12429:a=Sd("OpenGL_ES");break;default:return L=12300,0}return ud[b]=a},Ka:()=>{if(qd)if(h.me)if(h.me.isContextLost())L=12302;else return L=12288,1;else L=12290;else L=12289;return 0},La:(a,b)=>{if(62E3!=a)return L=12296,0;0==b?Pc(0,
0):Pc(1,b);L=12288;return 1},Ra:a=>{if(62E3!=a)return L=12296,0;td=sd=rd=0;qd=!1;L=12288;return 1},Na:()=>{L=12288;return 1},Ma:()=>{L=12288;return 1},T:(a,b,c)=>{b=Ud(b,c);return bb[a].apply(null,b)},b:(a,b,c)=>{b=Ud(b,c);return bb[a].apply(null,b)},hb:()=>Date.now(),xa:()=>{if(!ie())return-1;be(Ge);var a=xe[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Aa:()=>{be(He);if(document.exitPointerLock)document.exitPointerLock();
else return-1;return 0},f:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,d:(a,b,c)=>{a=U(a);if(!a)return-4;a=Fe(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},R:(a,b)=>{if(0>a||a>=ke.length)return-5;if(!ke[a])return-7;Ie(b,ke[a]);return 0},Za:()=>2147483648,n:Lc,$b:()=>ke.length,Pa:Je,Ea:(a,b,c)=>{a=qf(a);return(a=Pb[a])?Je(a.path,b,c):0},Ba:(a,b)=>{v[a>>2]=screen.width;v[b>>2]=screen.height},da:function(a){Q.activeTexture(a)},ca:(a,b)=>{Q.attachShader(N[a],O[b])},ta:(a,b)=>{Q.pe.beginQueryEXT(a,
Gd[b])},ba:(a,b,c)=>{Q.bindAttribLocation(N[a],b,c?D(r,c):"")},aa:(a,b)=>{Q.bindBuffer(a,Ad[b])},$:(a,b)=>{Q.bindFramebuffer(a,Bd[b])},_:(a,b)=>{Q.bindRenderbuffer(a,Cd[b])},Z:(a,b)=>{Q.bindTexture(a,Dd[b])},la:a=>{Q.bindVertexArray(Ed[a])},Y:function(a,b,c,d){Q.blendColor(a,b,c,d)},X:function(a){Q.blendEquation(a)},Md:function(a,b){Q.blendEquationSeparate(a,b)},Ld:function(a,b){Q.blendFunc(a,b)},Kd:function(a,b,c,d){Q.blendFuncSeparate(a,b,c,d)},Jd:(a,b,c,d)=>{Q.bufferData(a,c?r.subarray(c,c+b):
b,d)},Id:(a,b,c,d)=>{Q.bufferSubData(a,b,r.subarray(d,d+c))},Hd:function(a){return Q.checkFramebufferStatus(a)},Gd:function(a){Q.clear(a)},Fd:function(a,b,c,d){Q.clearColor(a,b,c,d)},Ed:function(a){Q.clearDepth(a)},Dd:function(a){Q.clearStencil(a)},Cd:(a,b,c,d)=>{Q.colorMask(!!a,!!b,!!c,!!d)},Bd:a=>{Q.compileShader(O[a])},Ad:(a,b,c,d,e,f,g,m)=>{Q.compressedTexImage2D(a,b,c,d,e,f,m?r.subarray(m,m+g):null)},zd:(a,b,c,d,e,f,g,m,n)=>{Q.compressedTexSubImage2D(a,b,c,d,e,f,g,n?r.subarray(n,n+m):null)},
yd:function(a,b,c,d,e,f,g,m){Q.copyTexImage2D(a,b,c,d,e,f,g,m)},xd:function(a,b,c,d,e,f,g,m){Q.copyTexSubImage2D(a,b,c,d,e,f,g,m)},wd:()=>{var a=Kd(N),b=Q.createProgram();b.name=a;b.He=b.Fe=b.Ge=0;b.Ve=1;N[a]=b;return a},vd:a=>{var b=Kd(O);O[b]=Q.createShader(a);return b},ud:function(a){Q.cullFace(a)},td:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Ad[d];e&&(Q.deleteBuffer(e),e.name=0,Ad[d]=null)}},sd:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=Bd[d];e&&(Q.deleteFramebuffer(e),e.name=0,Bd[d]=
null)}},rd:a=>{if(a){var b=N[a];b?(Q.deleteProgram(b),b.name=0,N[a]=null):P(1281)}},va:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Gd[d];e&&(Q.pe.deleteQueryEXT(e),Gd[d]=null)}},qd:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Cd[d];e&&(Q.deleteRenderbuffer(e),e.name=0,Cd[d]=null)}},pd:a=>{if(a){var b=O[a];b?(Q.deleteShader(b),O[a]=null):P(1281)}},od:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Dd[d];e&&(Q.deleteTexture(e),e.name=0,Dd[d]=null)}},ka:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+
4*c>>2];Q.deleteVertexArray(Ed[d]);Ed[d]=null}},nd:function(a){Q.depthFunc(a)},md:a=>{Q.depthMask(!!a)},ld:function(a,b){Q.depthRange(a,b)},kd:(a,b)=>{Q.detachShader(N[a],O[b])},jd:function(a){Q.disable(a)},hd:a=>{Q.disableVertexAttribArray(a)},gd:(a,b,c)=>{Q.drawArrays(a,b,c)},ga:(a,b,c,d)=>{Q.drawArraysInstanced(a,b,c,d)},ha:(a,b)=>{for(var c=Ke[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];Q.drawBuffers(c)},fd:(a,b,c,d)=>{Q.drawElements(a,b,c,d)},fa:(a,b,c,d,e)=>{Q.drawElementsInstanced(a,b,c,d,e)},ed:function(a){Q.enable(a)},
dd:a=>{Q.enableVertexAttribArray(a)},sa:a=>{Q.pe.endQueryEXT(a)},cd:function(){Q.finish()},bd:function(){Q.flush()},ad:(a,b,c,d)=>{Q.framebufferRenderbuffer(a,b,c,Cd[d])},$c:(a,b,c,d,e)=>{Q.framebufferTexture2D(a,b,c,Dd[d],e)},_c:function(a){Q.frontFace(a)},Yc:(a,b)=>{Le(a,b,"createBuffer",Ad)},Wc:(a,b)=>{Le(a,b,"createFramebuffer",Bd)},wa:(a,b)=>{for(var c=0;c<a;c++){var d=Q.pe.createQueryEXT();if(!d){for(P(1282);c<a;)v[b+4*c++>>2]=0;break}var e=Kd(Gd);d.name=e;Gd[e]=d;v[b+4*c>>2]=e}},Vc:(a,b)=>
{Le(a,b,"createRenderbuffer",Cd)},Uc:(a,b)=>{Le(a,b,"createTexture",Dd)},ja:function(a,b){Le(a,b,"createVertexArray",Ed)},Xc:function(a){Q.generateMipmap(a)},Tc:(a,b,c,d,e,f,g)=>{Me("getActiveAttrib",a,b,c,d,e,f,g)},Sc:(a,b,c,d,e,f,g)=>{Me("getActiveUniform",a,b,c,d,e,f,g)},Rc:(a,b,c,d)=>{a=Q.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);v[c>>2]=e;for(b=0;b<e;++b)v[d+4*b>>2]=O.indexOf(a[b])},Qc:(a,b)=>Q.getAttribLocation(N[a],b?D(r,b):""),Pc:(a,b)=>Ne(a,b,4),Nc:(a,b,c)=>{c?v[c>>2]=Q.getBufferParameter(a,
b):P(1281)},Mc:()=>{var a=Q.getError()||Jd;Jd=0;return a},Lc:(a,b)=>Ne(a,b,2),Kc:(a,b,c,d)=>{a=Q.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;v[d>>2]=a},Jc:(a,b)=>Ne(a,b,0),Hc:(a,b,c,d)=>{a=Q.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?H(a,r,d,b):0;c&&(v[c>>2]=b)},Ic:(a,b,c)=>{if(c)if(a>=zd)P(1281);else if(a=N[a],35716==b)a=Q.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==
b){if(!a.He)for(b=0;b<Q.getProgramParameter(a,35718);++b)a.He=Math.max(a.He,Q.getActiveUniform(a,b).name.length+1);v[c>>2]=a.He}else if(35722==b){if(!a.Fe)for(b=0;b<Q.getProgramParameter(a,35721);++b)a.Fe=Math.max(a.Fe,Q.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.Fe}else if(35381==b){if(!a.Ge)for(b=0;b<Q.getProgramParameter(a,35382);++b)a.Ge=Math.max(a.Ge,Q.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Ge}else v[c>>2]=Q.getProgramParameter(a,b);else P(1281)},na:Oe,pa:Pe,ma:Oe,oa:Pe,qa:(a,
b,c)=>{c?v[c>>2]=Q.pe.getQueryEXT(a,b):P(1281)},Gc:(a,b,c)=>{c?v[c>>2]=Q.getRenderbufferParameter(a,b):P(1281)},Ec:(a,b,c,d)=>{a=Q.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?H(a,r,d,b):0;c&&(v[c>>2]=b)},Dc:(a,b,c,d)=>{a=Q.getShaderPrecisionFormat(a,b);v[c>>2]=a.rangeMin;v[c+4>>2]=a.rangeMax;v[d>>2]=a.precision},Cc:(a,b,c,d)=>{if(a=Q.getShaderSource(O[a]))b=0<b&&d?H(a,r,d,b):0,c&&(v[c>>2]=b)},Fc:(a,b,c)=>{c?35716==b?(a=Q.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),v[c>>
2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(O[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=Q.getShaderParameter(O[a],b):P(1281)},Bc:a=>{var b=Hd[a];if(!b){switch(a){case 7939:b=Sd(Qd().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Q.getParameter(a))||P(1280);b=b?Sd(b):0;break;case 7938:b=Sd(`OpenGL ES 2.0 (${Q.getParameter(7938)})`);break;case 35724:b=Q.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);
b=Sd(b);break;default:P(1280)}Hd[a]=b}return b},Ac:(a,b,c)=>{c?y[c>>2]=Q.getTexParameter(a,b):P(1281)},zc:(a,b,c)=>{c?v[c>>2]=Q.getTexParameter(a,b):P(1281)},wc:(a,b)=>{b=b?D(r,b):"";if(a=N[a]){Re(a);var c=a.Ce,d=0,e=b,f=Qe(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.pf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||Q.getUniformLocation(a,b)))return d}else P(1281);return-1},yc:(a,b,c)=>{Se(a,b,c,2)},xc:(a,b,c)=>{Se(a,b,c,0)},tc:(a,b,c)=>{c?v[c>>2]=Q.getVertexAttribOffset(a,b):P(1281)},vc:(a,b,
c)=>{Te(a,b,c,2)},uc:(a,b,c)=>{Te(a,b,c,5)},sc:function(a,b){Q.hint(a,b)},rc:a=>(a=Ad[a])?Q.isBuffer(a):0,qc:function(a){return Q.isEnabled(a)},pc:a=>(a=Bd[a])?Q.isFramebuffer(a):0,oc:a=>(a=N[a])?Q.isProgram(a):0,ua:a=>(a=Gd[a])?Q.pe.isQueryEXT(a):0,nc:a=>(a=Cd[a])?Q.isRenderbuffer(a):0,mc:a=>(a=O[a])?Q.isShader(a):0,lc:a=>(a=Dd[a])?Q.isTexture(a):0,ia:a=>(a=Ed[a])?Q.isVertexArray(a):0,kc:function(a){Q.lineWidth(a)},jc:a=>{a=N[a];Q.linkProgram(a);a.Ce=0;a.pf={}},ic:(a,b)=>{3317==a&&(Id=b);Q.pixelStorei(a,
b)},hc:function(a,b){Q.polygonOffset(a,b)},ra:(a,b)=>{Q.pe.queryCounterEXT(Gd[a],b)},gc:(a,b,c,d,e,f,g)=>{(g=Ue(f,e,c,d,g))?Q.readPixels(a,b,c,d,e,f,g):P(1280)},fc:()=>{},ec:function(a,b,c,d){Q.renderbufferStorage(a,b,c,d)},dc:(a,b)=>{Q.sampleCoverage(a,!!b)},cc:function(a,b,c,d){Q.scissor(a,b,c,d)},bc:()=>{P(1280)},ac:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=d?v[d+4*f>>2]:-1,m=v[c+4*f>>2];g=m?D(r,m,0>g?void 0:g):"";e+=g}Q.shaderSource(O[a],e)},_b:function(a,b,c){Q.stencilFunc(a,b,c)},Zb:function(a,
b,c,d){Q.stencilFuncSeparate(a,b,c,d)},Yb:function(a){Q.stencilMask(a)},Xb:function(a,b){Q.stencilMaskSeparate(a,b)},Wb:function(a,b,c){Q.stencilOp(a,b,c)},Vb:function(a,b,c,d){Q.stencilOpSeparate(a,b,c,d)},Ub:(a,b,c,d,e,f,g,m,n)=>{Q.texImage2D(a,b,c,d,e,f,g,m,n?Ue(m,g,d,e,n):null)},Tb:function(a,b,c){Q.texParameterf(a,b,c)},Sb:(a,b,c)=>{Q.texParameterf(a,b,y[c>>2])},Rb:function(a,b,c){Q.texParameteri(a,b,c)},Pb:(a,b,c)=>{Q.texParameteri(a,b,v[c>>2])},Ob:(a,b,c,d,e,f,g,m,n)=>{var p=null;n&&(p=Ue(m,
g,e,f,n));Q.texSubImage2D(a,b,c,d,e,f,g,m,p)},Nb:(a,b)=>{Q.uniform1f(V(a),b)},Mb:(a,b,c)=>{if(288>=b)for(var d=Ve[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);Q.uniform1fv(V(a),d)},Lb:(a,b)=>{Q.uniform1i(V(a),b)},Kb:(a,b,c)=>{if(288>=b)for(var d=We[b-1],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);Q.uniform1iv(V(a),d)},Jb:(a,b,c)=>{Q.uniform2f(V(a),b,c)},Ib:(a,b,c)=>{if(144>=b)for(var d=Ve[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=
y.subarray(c>>2,c+8*b>>2);Q.uniform2fv(V(a),d)},Hb:(a,b,c)=>{Q.uniform2i(V(a),b,c)},Gb:(a,b,c)=>{if(144>=b)for(var d=We[2*b-1],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2];else d=v.subarray(c>>2,c+8*b>>2);Q.uniform2iv(V(a),d)},Fb:(a,b,c,d)=>{Q.uniform3f(V(a),b,c,d)},Eb:(a,b,c)=>{if(96>=b)for(var d=Ve[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);Q.uniform3fv(V(a),d)},Db:(a,b,c,d)=>{Q.uniform3i(V(a),b,c,d)},Cb:(a,b,
c)=>{if(96>=b)for(var d=We[3*b-1],e=0;e<3*b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2];else d=v.subarray(c>>2,c+12*b>>2);Q.uniform3iv(V(a),d)},Bb:(a,b,c,d,e)=>{Q.uniform4f(V(a),b,c,d,e)},Ab:(a,b,c)=>{if(72>=b){var d=Ve[4*b-1],e=y;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=y.subarray(c>>2,c+16*b>>2);Q.uniform4fv(V(a),d)},zb:(a,b,c,d,e)=>{Q.uniform4i(V(a),b,c,d,e)},yb:(a,b,c)=>{if(72>=b)for(var d=We[4*b-1],e=0;e<4*b;e+=
4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2];else d=v.subarray(c>>2,c+16*b>>2);Q.uniform4iv(V(a),d)},xb:(a,b,c,d)=>{if(72>=b)for(var e=Ve[4*b-1],f=0;f<4*b;f+=4)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2];else e=y.subarray(d>>2,d+16*b>>2);Q.uniformMatrix2fv(V(a),!!c,e)},wb:(a,b,c,d)=>{if(32>=b)for(var e=Ve[9*b-1],f=0;f<9*b;f+=9)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2],
e[f+4]=y[d+(4*f+16)>>2],e[f+5]=y[d+(4*f+20)>>2],e[f+6]=y[d+(4*f+24)>>2],e[f+7]=y[d+(4*f+28)>>2],e[f+8]=y[d+(4*f+32)>>2];else e=y.subarray(d>>2,d+36*b>>2);Q.uniformMatrix3fv(V(a),!!c,e)},vb:(a,b,c,d)=>{if(18>=b){var e=Ve[16*b-1],f=y;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+
15]}}else e=y.subarray(d>>2,d+64*b>>2);Q.uniformMatrix4fv(V(a),!!c,e)},ub:a=>{a=N[a];Q.useProgram(a);Q.wf=a},tb:a=>{Q.validateProgram(N[a])},sb:function(a,b){Q.vertexAttrib1f(a,b)},rb:(a,b)=>{Q.vertexAttrib1f(a,y[b>>2])},qb:function(a,b,c){Q.vertexAttrib2f(a,b,c)},pb:(a,b)=>{Q.vertexAttrib2f(a,y[b>>2],y[b+4>>2])},ob:function(a,b,c,d){Q.vertexAttrib3f(a,b,c,d)},nb:(a,b)=>{Q.vertexAttrib3f(a,y[b>>2],y[b+4>>2],y[b+8>>2])},mb:function(a,b,c,d,e){Q.vertexAttrib4f(a,b,c,d,e)},lb:(a,b)=>{Q.vertexAttrib4f(a,
y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},ea:(a,b)=>{Q.vertexAttribDivisor(a,b)},kb:(a,b,c,d,e,f)=>{Q.vertexAttribPointer(a,b,c,!!d,e,f)},jb:function(a,b,c,d){Q.viewport(a,b,c,d)},o:()=>0,ib:(a,b,c)=>r.copyWithin(a,b,b+c),ya:(a,b,c)=>Xe(a,{Te:v[c>>2],Le:v[c+4>>2],Df:v[c+8>>2],Af:b,De:v[c+12>>2],Ze:v[c+16>>2]}),K:(a,b)=>{a=U(a);return a?a.requestPointerLock?ce()?He(a):b?(ae(He,2,[a]),1):-2:-1:-4},Ya:a=>{var b=r.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,
a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-va.buffer.byteLength+65535)/65536;try{va.grow(e);Aa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},S:()=>(ke=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1,q:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Ye(a,b),C:(a,b,c,d)=>Ze(a,b,c,d,12,"blur"),e:Be,l:(a,b,c)=>{a=U(a);if(!a)return-4;a.style.width=b+"px";a.style.height=
c+"px";return 0},D:(a,b,c,d)=>Ze(a,b,c,d,13,"focus"),t:(a,b,c,d)=>{if(!ie())return-1;a=U(a);if(!a)return-4;$e(a,b,c,d,"webkitfullscreenchange");return $e(a,b,c,d,"fullscreenchange")},Q:(a,b,c)=>navigator.getGamepads||navigator.webkitGetGamepads?af(a,b,c,26,"gamepadconnected"):-1,P:(a,b,c)=>navigator.getGamepads||navigator.webkitGetGamepads?af(a,b,c,27,"gamepaddisconnected"):-1,w:(a,b,c,d)=>bf(a,b,c,d,2,"keydown"),u:(a,b,c,d)=>bf(a,b,c,d,1,"keypress"),v:(a,b,c,d)=>bf(a,b,c,d,3,"keyup"),Qb:(a,b,c)=>
{a=I(a);Yc(a,b,c)},I:(a,b,c,d)=>df(a,b,c,d,5,"mousedown"),G:(a,b,c,d)=>df(a,b,c,d,33,"mouseenter"),F:(a,b,c,d)=>df(a,b,c,d,34,"mouseleave"),J:(a,b,c,d)=>df(a,b,c,d,8,"mousemove"),H:(a,b,c,d)=>df(a,b,c,d,6,"mouseup"),x:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.de||document.body.tf||document.body.ze))return-1;a=U(a);if(!a)return-4;ef(a,b,c,d,"mozpointerlockchange");ef(a,b,c,d,"webkitpointerlockchange");ef(a,b,c,d,"mspointerlockchange");return ef(a,b,
c,d,"pointerlockchange")},s:(a,b,c,d)=>ff(a,b,c,d),y:(a,b,c,d)=>gf(a,b,c,d,25,"touchcancel"),A:(a,b,c,d)=>gf(a,b,c,d,23,"touchend"),z:(a,b,c,d)=>gf(a,b,c,d,24,"touchmove"),B:(a,b,c,d)=>gf(a,b,c,d,22,"touchstart"),r:(a,b,c)=>xe[1]?hf(a,b,c):-4,E:(a,b,c,d)=>(a=U(a))?"undefined"!=typeof a.onwheel?jf(a,b,c,d):-1:-4,za:a=>document.title=a?D(r,a):"",m:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},ab:(a,b)=>{var c=0;mf().forEach((d,
e)=>{var f=b+c;e=w[a+4*e>>2]=f;for(f=0;f<d.length;++f)l[e++>>0]=d.charCodeAt(f);l[e>>0]=0;c+=d.length+1});return 0},bb:(a,b)=>{var c=mf();w[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);w[b>>2]=d;return 0},p:$c,O:function(a){try{var b=dc(a);rc(b);return 0}catch(c){if("undefined"==typeof Bc||"ErrnoError"!==c.name)throw c;return c.ke}},db:function(a,b,c,d){try{a:{var e=dc(a);a=b;for(var f,g=b=0;g<c;g++){var m=w[a>>2],n=w[a+4>>2];a+=8;var p=e,u=m,q=n,t=f,x=l;if(0>q||0>t)throw new J(28);if(null===
p.fd)throw new J(8);if(1===(p.flags&2097155))throw new J(8);if(Cb(p.node.mode))throw new J(31);if(!p.be.read)throw new J(28);var B="undefined"!=typeof t;if(!B)t=p.position;else if(!p.seekable)throw new J(70);var G=p.be.read(p,x,u,q,t);B||(p.position+=G);var E=G;if(0>E){var S=-1;break a}b+=E;if(E<n)break;"undefined"!==typeof f&&(f+=E)}S=b}w[d>>2]=S;return 0}catch(ea){if("undefined"==typeof Bc||"ErrnoError"!==ea.name)throw ea;return ea.ke}},Ta:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+
4294967296*c:NaN;try{if(isNaN(b))return 61;var f=dc(a);sc(f,b,d);C=[f.position>>>0,(A=f.position,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[e>>2]=C[0];v[e+4>>2]=C[1];f.Oe&&0===b&&0===d&&(f.Oe=null);return 0}catch(g){if("undefined"==typeof Bc||"ErrnoError"!==g.name)throw g;return g.ke}},M:function(a,b,c,d){try{a:{var e=dc(a);a=b;for(var f,g=b=0;g<c;g++){var m=w[a>>2],n=w[a+4>>2];a+=8;var p=tc(e,l,m,n,f);if(0>p){var u=-1;break a}b+=p;"undefined"!==
typeof f&&(f+=p)}u=b}w[d>>2]=u;return 0}catch(q){if("undefined"==typeof Bc||"ErrnoError"!==q.name)throw q;return q.ke}},i:rf,g:sf,h:tf,k:uf,id:vf,Zc:wf,U:xf,Va:yf,Ua:zf,c:Af,j:Bf,V:Cf,a:va},Y=function(){function a(c){Y=c.exports;Va();fb=Y.Qd;Da.unshift(Y.Nd);Ma("wasm-instantiate");return Y}var b={a:Df};La("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return k(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ta(b,function(c){a(c.instance)});return{}}(),
F=a=>(F=Y.Od)(a),Ef=h._main=(a,b)=>(Ef=h._main=Y.Pd)(a,b),pf=()=>(pf=Y.Rd)(),qf=a=>(qf=Y.Sd)(a),xb=(a,b)=>(xb=Y.Td)(a,b),Z=(a,b)=>(Z=Y.Ud)(a,b),R=()=>(R=Y.Vd)(),T=a=>(T=Y.Wd)(a),ye=a=>(ye=Y.Xd)(a),Ff=h.dynCall_ji=(a,b)=>(Ff=h.dynCall_ji=Y.Yd)(a,b),Gf=h.dynCall_jiji=(a,b,c,d,e)=>(Gf=h.dynCall_jiji=Y.Zd)(a,b,c,d,e);h.dynCall_iiji=(a,b,c,d,e)=>(h.dynCall_iiji=Y._d)(a,b,c,d,e);function rf(a,b){var c=R();try{return I(a)(b)}catch(d){T(c);if(d!==d+0)throw d;Z(1,0)}}
function uf(a,b,c,d,e){var f=R();try{return I(a)(b,c,d,e)}catch(g){T(f);if(g!==g+0)throw g;Z(1,0)}}function tf(a,b,c,d){var e=R();try{return I(a)(b,c,d)}catch(f){T(e);if(f!==f+0)throw f;Z(1,0)}}function Af(a,b){var c=R();try{I(a)(b)}catch(d){T(c);if(d!==d+0)throw d;Z(1,0)}}function sf(a,b,c){var d=R();try{return I(a)(b,c)}catch(e){T(d);if(e!==e+0)throw e;Z(1,0)}}function Cf(a,b,c,d){var e=R();try{I(a)(b,c,d)}catch(f){T(e);if(f!==f+0)throw f;Z(1,0)}}
function Bf(a,b,c){var d=R();try{I(a)(b,c)}catch(e){T(d);if(e!==e+0)throw e;Z(1,0)}}function xf(a,b,c,d,e,f,g,m,n,p){var u=R();try{return I(a)(b,c,d,e,f,g,m,n,p)}catch(q){T(u);if(q!==q+0)throw q;Z(1,0)}}function vf(a,b,c,d,e,f){var g=R();try{return I(a)(b,c,d,e,f)}catch(m){T(g);if(m!==m+0)throw m;Z(1,0)}}function wf(a,b,c,d,e,f,g,m,n){var p=R();try{return I(a)(b,c,d,e,f,g,m,n)}catch(u){T(p);if(u!==u+0)throw u;Z(1,0)}}
function yf(a,b){var c=R();try{return Ff(a,b)}catch(d){T(c);if(d!==d+0)throw d;Z(1,0)}}function zf(a,b,c,d,e){var f=R();try{return Gf(a,b,c,d,e)}catch(g){T(f);if(g!==g+0)throw g;Z(1,0)}}h.addRunDependency=La;h.removeRunDependency=Ma;h.FS_createPath=wc;h.FS_createLazyFile=Ac;h.FS_createDevice=yc;h.FS_createPreloadedFile=Lb;h.FS_createDataFile=Kb;h.FS_unlink=nc;h.allocate=Wa;var Hf;Ka=function If(){Hf||Jf();Hf||(Ka=If)};
function Kf(a=[]){var b=Ef;a.unshift(ca);var c=a.length,d=ye(4*(c+1)),e=d;a.forEach(g=>{w[e>>2]=ze(g);e+=4});w[e>>2]=0;try{var f=b(c,d);$c(f,!0)}catch(g){Xc(g)}}
function Jf(){var a=ba;function b(){if(!Hf&&(Hf=!0,h.calledRun=!0,!wa)){h.noFSInit||vc||(vc=!0,uc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?yc("/dev","stdin",h.stdin):lc("/dev/tty","/dev/stdin"),h.stdout?yc("/dev","stdout",null,h.stdout):lc("/dev/tty","/dev/stdout"),h.stderr?yc("/dev","stderr",null,h.stderr):lc("/dev/tty1","/dev/stderr"),pc("/dev/stdin",0),pc("/dev/stdout",1),pc("/dev/stderr",1));Sb=!1;db(Da);db(Ea);if(h.onRuntimeInitialized)h.onRuntimeInitialized();Lf&&Kf(a);
if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Ga.unshift(c)}db(Ga)}}if(!(0<Ia)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ha();db(Ca);0<Ia||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Lf=!0;
h.noInitialRun&&(Lf=!1);Jf();
